# Generated by Django 6.0.7 on 2026-07-09 17:47

import employees.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('department', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('joining_date', models.DateField()),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='employees/photos/', validators=[employees.validators.validate_image])),
                ('resume', models.FileField(blank=True, null=True, upload_to='employees/resumes/', validators=[employees.validators.validate_document])),
                ('aadhaar_document', models.FileField(blank=True, null=True, upload_to='employees/aadhaar/', validators=[employees.validators.validate_document])),
                ('pan_document', models.FileField(blank=True, null=True, upload_to='employees/pan/', validators=[employees.validators.validate_document])),
            ],
        ),
    ]
