from io import BytesIO
import os

from django.http import HttpResponse
from reportlab.lib.colors import blue, black
from reportlab.lib.pagesizes import landscape
from reportlab.pdfgen import canvas

from employees.models import Employee
from .qr_generation import generate_employee_qr


def generate_id_card(employee_id):
    employee = Employee.objects.get(id=employee_id)

    buffer = BytesIO()

    pdf = canvas.Canvas(buffer, pagesize=landscape((350, 200)))

    # Border
    pdf.rect(10, 10, 330, 180)

    # Company Name
    pdf.setFont("Helvetica-Bold", 18)
    pdf.setFillColor(blue)
    pdf.drawString(20, 170, "COMPANY HR PORTAL")

    # Employee Details
    pdf.setFillColor(black)
    pdf.setFont("Helvetica", 11)

    pdf.drawString(20, 145, f"Employee ID : {employee.employee_id}")
    pdf.drawString(20, 125, f"Name : {employee.first_name} {employee.last_name}")
    pdf.drawString(20, 105, f"Department : {employee.department}")
    pdf.drawString(20, 85, f"Designation : {employee.designation}")
    pdf.drawString(20, 65, f"Email : {employee.email}")

    # Employee Photo
    if employee.profile_photo:
        try:
            if os.path.exists(employee.profile_photo.path):
                pdf.drawImage(
                    employee.profile_photo.path,
                    250,
                    95,
                    width=70,
                    height=70,
                    preserveAspectRatio=True,
                    mask="auto",
                )
        except Exception:
            pass

    # Generate and Draw QR Code
    try:
        qr_path = generate_employee_qr(employee)

        if os.path.exists(qr_path):
            pdf.drawImage(
                qr_path,
                250,
                20,
                width=60,
                height=60,
                preserveAspectRatio=True,
                mask="auto",
            )
    except Exception:
        pass

    pdf.setFont("Helvetica-Oblique", 8)
    pdf.drawString(20, 20, "Generated by Company HR Portal")

    pdf.showPage()
    pdf.save()

    pdf_data = buffer.getvalue()
    buffer.close()

    response = HttpResponse(pdf_data, content_type="application/pdf")
    response["Content-Disposition"] = (
        f'attachment; filename="employee_{employee.employee_id}_id_card.pdf"'
    )

    return response